on:
  tags:
    - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: "20"

      - run: pnpm install

      - name: query api to get all repos
        id: get_repos
        uses: actions/github-script@v7
        env:
          GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN_FOR_PR_AUTOMATION }}
          with:
          github-token: ${{ secrets.ACCESS_TOKEN_FOR_PR_AUTOMATION }}
          script: |
            const script = await import('${{ github.workspace }}/src/index.js');
            const repos = await script(github, 'MultiRepoActions');
            return repos

      # not sure if this will work, so lets try and show the result

      - name: show result of get_repos
        run: echo ${{ steps.get_repos.outputs.result }}
